### ISSUE TITLE
error: could not find native static library `bpf`

### ISSUE THREAD

**Issue by KarstenB** [chenhengqi/libxdp-sys#5]
When using the library, the bpf library could not be found. This is most likely caused by a missing call to `make` in the `build.rs`.
Something like this should do the trick (untested):
```rust
    let status = process::Command::new("make")
        .current_dir(& libbpf_dir)
        .status()
        .expect("could not execute make");
```

**Comment by KarstenB** [comment]
I have a proposal PR #9. If you want to use it right now, the easiest way is to add the following lines to your `.cargo/config.toml`:
```toml
[patch.crates-io]
libxdp-sys = { git = "https://github.com/KarstenB/libxdp-sys.git", branch = "update_xdp_tools" }
```
